/**
 * Paralives Guide — canonical、OG、Twitter、sitemap 使用此域名。
 */
export const seoConfig = {
  domain: 'paralivesguides.org',
  fullDomain: 'https://paralivesguides.org',
  siteName: 'Paralives Guide',
  /** 分享图；生产环境 documentMeta 会转为绝对 URL */
  defaultOgImage: '/images/logo.png',
  defaults: {
    title: 'Paralives Guide — Wiki, Cheats, Mods & Melino Map for EA',
    description:
      'We play Paralives on Steam EA and write what works — wiki topics, first-save tips, cheats to verify with HELP, Workshop mods we keep, and a Melino pin map.',
    keywords:
      'Paralives, Paralives game, Paralives Guide, Paralives Steam, Paralives Early Access, Paralives wiki, Paralives cheats, Paralives mods, Melino map',
    author: 'Paralives Guide',
    type: 'website',
  },
  priorities: {
    home: 1.0,
    'how-to-play': 0.95,
    wiki: 0.92,
    'wiki-talents': 0.85,
    'wiki-vibes': 0.85,
    'wiki-skills': 0.85,
    'wiki-skills-leveling': 0.82,
    'wiki-traits': 0.85,
    'wiki-emotions': 0.85,
    'wiki-needs-wants': 0.85,
    'wiki-parafolks': 0.85,
    'wiki-build-tools': 0.85,
    'wiki-careers': 0.85,
    'wiki-careers-occupations': 0.82,
    'wiki-careers-economy': 0.82,
    'wiki-relationships': 0.85,
    'wiki-modding': 0.85,
    guides: 0.9,
    'guide-detail': 0.8,
    build: 0.88,
    cheats: 0.88,
    mods: 0.88,
    updates: 0.9,
    map: 0.9,
    'legal-privacy': 0.35,
    'legal-terms': 0.35,
    'legal-copyright': 0.35,
    'legal-about': 0.45,
    'legal-contact': 0.45,
  },
  changefreq: {
    home: 'weekly',
    'how-to-play': 'weekly',
    wiki: 'weekly',
    'wiki-talents': 'weekly',
    'wiki-vibes': 'weekly',
    'wiki-skills': 'weekly',
    'wiki-skills-leveling': 'weekly',
    'wiki-traits': 'weekly',
    'wiki-emotions': 'weekly',
    'wiki-needs-wants': 'weekly',
    'wiki-parafolks': 'weekly',
    'wiki-build-tools': 'weekly',
    'wiki-careers': 'weekly',
    'wiki-careers-occupations': 'weekly',
    'wiki-careers-economy': 'weekly',
    'wiki-relationships': 'weekly',
    'wiki-modding': 'weekly',
    guides: 'weekly',
    'guide-detail': 'monthly',
    build: 'weekly',
    cheats: 'weekly',
    mods: 'weekly',
    updates: 'weekly',
    map: 'weekly',
    'legal-privacy': 'yearly',
    'legal-terms': 'yearly',
    'legal-copyright': 'yearly',
    'legal-about': 'yearly',
    'legal-contact': 'yearly',
  },
}
